### ISSUE TITLE
Носок

### ISSUE THREAD

**Issue by NastyaLosik** [Koozkoo/Lost_Sock#1]
![image](https://user-images.githubusercontent.com/117820351/224902929-5f1f72fa-f03c-4946-a59c-0f1471ce0249.png)
![image](https://user-images.githubusercontent.com/117820351/224903284-f2db915e-99bf-4a73-b24f-119ba34196bf.png)![image](https://user-images.githubusercontent.com/117820351/224903362-fbfa4a54-95a7-498d-93bb-4f70ca043d82.png)

**Comment by Koozkoo** [comment]
all good
